# Generated by Django 3.2.16 on 2022-12-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='strip_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
